### ISSUE TITLE
Orga: Punkte pro Blatt: TDU => Note, FHB => Testat

### ISSUE THREAD

**Issue by cagix** [KI-Vorlesung/Lecture#10]
Absprache bzgl. der Punkte pro Blatt: TDU => Note, FHB => Testat

**Comment by cyildiz** [comment]
Wie wäre es, wenn wir beide jeweils 50 Punkte unter den eigenen 6 Blättern verteilen?
Insgesamt gibt es dann 100 Übungspunkte und die Note ist einfach berechnet.

**Comment by cagix** [comment]
100 Punkte gesamt lassen sich gut auf die Note oder das Testat verrechnen. 👍  

Andererseits fände ich 10P je Blatt irgendwie auch nett? Mit 100P gesamt kommen wir im Mittel auf 8.33P je Blatt ...

**Comment by cagix** [comment]
@cyildiz ich hatte ja die idee, die challenges als bonus-aufgaben zu übernehmen. 

das könnten 2..4 punkte bonus (auf ausgewählten blättern) sein. sollen wir das so machen? passt das zu deinem grading-schema oder willst die bonuspunkte evtl. sogar analog zur aktiven beteiligung mit für die note berücksichtigen?

**Comment by cagix** [comment]
10P je Blatt, 120P gesamt => Note / Testat

**Comment by cagix** [comment]
Blatt 01 (Problemlösen) und Blatt 02 (Suche) zusammenfassen, analog bei Perzeptron/Regression

=> in Summe 10 Blätter mit je 10 Punkten

=> **Blatt zum Stoff einer Woche ist in der selben Woche abzugeben (Zwang zur aktiven Vorbereitung)**!

**Comment by cagix** [comment]
@cyildiz Schau mal bitte auf den Schedule in #59, ich habe den Schedule entsprechend angepasst. Wir hatten ja am Freitag 10 Blätter (jeder 5) besprochen. Passt das so für Dich? Ich war mir nicht sicher, wie Du Deine 5 Blätter dann verteilen willst. Die erste Woche im neuen Jahr hätte dann kein Blatt?

**Comment by cyildiz** [comment]
@cagix , auf den branches orga und schedule erhalte ich folgende fehlermeldung bei `make web`:
<img width="994" alt="image" src="https://user-images.githubusercontent.com/1532767/134808114-3a7955ad-4867-4fa4-8f01-30d97d945a88.png">

**Comment by cagix** [comment]
> @cagix , auf den branches orga und schedule erhalte ich folgende fehlermeldung bei `make web`:
> <img alt="image" width="994" src="https://user-images.githubusercontent.com/1532767/134808114-3a7955ad-4867-4fa4-8f01-30d97d945a88.png">

oh mist, ich wollte alle übungsblätter auf "sketch" stellen und habe bei b10 den yaml-header kaputt gemacht :( ... sollte im `orga`-branch jetzt behoben sein.

im `schedule` habe ich nur die `schedule.yaml` angepast, aber ich kann den branch nochmal rebasen, damit du das bauen kannst.

**Comment by cyildiz** [comment]
Jetzt funktioniert's, danke!
Du hast in Woche 7 kein Übungsblatt, das ist Absicht, oder?
Oder hast Du ein Blatt ausgelassen um auf 5 zu kommen?

**Comment by cagix** [comment]
hmmm, wir hatten am freitag über 2x5 blätter gesprochen. insofern habe ich für woche 7 kein blatt mehr.

**Comment by cagix** [comment]
das ist bei dir am jahresanfang dann aber auch so!

**Comment by cagix** [comment]
oder sollen wir doch wieder auf 12 blätter gehen?

**Comment by cagix** [comment]
irgendwie hatten wir das scheinbar beide nicht auf dem schirm, als wir freitag telefoniert hatten ;)

**Comment by cagix** [comment]
mir ist das eher egal. wir können bei 10 bleiben, dann ist eben ne lücke, oder doch auf 12 blätter gehen ...

**Comment by cyildiz** [comment]
Ich würde eigentlich keine explizite auf die Gesamtanzahl der UE-Blätter setzen.
Ich würde mich nach Dir richten.
Wenn Du normalerweise ein Blatt für Naive Bayes hast und damit insgesamt auf 6 Blätter kommst, 
dann kann ich auch 6 Blätter einrichten.
Sonst kann ich auch 5 Blätter einrichten :)

**Comment by cyildiz** [comment]
> irgendwie hatten wir das scheinbar beide nicht auf dem schirm, als wir freitag telefoniert hatten ;)

Genau, bei den Übungen verliere ich immer den Überblick. Da ist nichts auf dem Schirm :)

**Comment by cyildiz** [comment]
Wenn Du keine Präferenz hast, plane ich 5 Blätter?

**Comment by cagix** [comment]
> Wenn Du normalerweise ein Blatt für Naive Bayes hast 

hatte ich bisher nicht, müsste ich dieses jahr dann neu machen.

> Ich würde eigentlich keine explizite Grenze auf die Gesamtanzahl der UE-Blätter setzen.

ich muss das leider schon fixieren, da es ja prüfungsrelevant ist. d.h. das muss bei mir von anfang an klar definiert sein.

> Wenn Du keine Präferenz hast, plane ich 5 Blätter?

okay, dann machen wir jeder 5 blätter.

**Comment by cyildiz** [comment]
> ich muss das leider schon fixieren, da es ja prüfungsrelevant ist. d.h. das muss bei mir von anfang an klar definiert sein.

Ja, natürlich. Ich meinte nur die jetzige Planungsphase. 

> hatte ich bisher nicht, müsste ich dieses jahr dann neu machen.

Passt! Das war genau meine Frage:
ob Du ein bisher genutztes Übungsblatt jetzt auf Grund einer Obergrenze weglässt.

Dann passe ich das Schedule für meinen Teil gleich an (auf 5 Blätter).

**Comment by cagix** [comment]
> Dann passe ich das Schedule für meinen Teil gleich an (auf 5 Blätter).

habe ich im "schedule"-branch schon gemacht. schau mal, ob das für dich passt.

**Comment by cagix** [comment]
wenn du die letzten beiden blätter zusammenfasst, also B10 == "Backpropagation, Training & Testing", dann sollte b10 jeweils eine woche später abgegeben werden, da es sonst nicht mehr zu den vorlesungen passt

**Comment by cyildiz** [comment]
ok, ich habe mir die letzten änderungen auf schedule heruntergeholt und mache jetzt einige anpassungen 👍

**Comment by cagix** [comment]
ack. sag kurz bescheid, wenn du damit durch bist, dann übernehme ich den branch wieder und schaue nochmal alles in ruhe durch und merge das endlich :)

**Comment by cyildiz** [comment]
Habe eben eine Überarbeitung hochgeladen.
Die Notizen in der Vorlesung-Spalte, unterhalb der `<ul>`-items hatte ich während der planung eingefügt, um nicht die übersicht zu verlieren, wann was geschieht (als Hilfe bei der Planung).

@cagix : Wenn Du denkst Du, dass diese im Schedule jetzt zu viel clutter verursachen und die Seite unübersichtlich machen, können wir die vielleicht wieder löschen?

**Comment by cagix** [comment]
> @cagix : Wenn Du denkst Du, dass diese im Schedule jetzt zu viel clutter verursachen und die Seite unübersichtlich machen, können wir die vielleicht wieder löschen?

hmmm, das ist leicht redundant, wenn man sich die bedeutung der spalten überlegt und eine gewisse fehlerquelle für uns (muss immer mit bedacht werden). aber andererseits ist es für die studis vielleicht hilfreicher so? ich würde es jetzt einfach drin lassen.

**Comment by cyildiz** [comment]
> wenn du die letzten beiden blätter zusammenfasst, also B10 == "Backpropagation, Training & Testing", dann sollte b10 jeweils eine woche später abgegeben werden, da es sonst nicht mehr zu den vorlesungen passt

Vollständigkeitshalber zur Info: Letztes Blatt B10 = Backpropagation.
Kein Blatt zu Training & Testing.
