### ISSUE TITLE
[BUG] Ergebnisse Ilias Test "Einführung Maschinelles Lernen" nicht einsehbar

### ISSUE THREAD

**Issue by Ironeer** [KI-Vorlesung/Lecture#115]
**Describe the bug**
Nach Abschluss des neuen Ilias Tests/Quizzes wird für die Ergebnisse des Testdurchlaufs der Button "Detaillierte Ergebnisse" nicht angezeigt. Man kann also nicht sehen welche Antworten falsch waren.

**To Reproduce**
Quiz "Einführung Maschinelles Lernen" abschließen und danach auf der Ergebnis-Seite des Tests versuchen die einzelnen Ergebnisse der Antworten zu sehen.

**Comment by cagix** [comment]
oh, sorry. wird behoben.

**Comment by cagix** [comment]
@Ironeer Sollte gefixt sein. Bitte prüfen und das Ticket ggf. nochmal aufmachen! Danke für den Hinweis :)
