### ISSUE TITLE
Fragen für die Umfrage

### ISSUE THREAD

**Issue by cagix** [KI-Vorlesung/Lecture#123]
Wie heute besprochen sammeln wir in diesem Ticket Fragen, die wie in der Umfrage von Digital Mobil noch ergänzen wollen. Ziel sollte sein, am Fr, 10.12., ein paar Fragen an Felix weiterleiten zu können.

Also: Was wollen wir von den Studis noch alles wissen?

**Comment by cagix** [comment]
Welche der angebotenen Materialien haben Sie zum Lernen und zum Lösen der Übungsblätter regelmäßig genutzt?

Matrix: Zeilen (Skript/Webseite, Video, Kahoot, ILIAS-Selbsttest); Spalten (häufig, ..., selten, nie)

**Comment by cagix** [comment]
Kennen Sie das Format "Flipped Classroom"? Was würden Sie sich von der Sprechstunde wünschen?

**Comment by cagix** [comment]
Wir hatten Ihnen angeboten, in den Praktika/Übungen die Hochschule zu wechseln. Wie beurteilen Sie dieses Angebot? Was wäre für Sie ein Anreiz, am Praktikum oder an der Übung an der jeweiligen Partnerhochschule teilzunehmen?

**Comment by jposselt** [comment]
Vielleicht noch eine Frage wie gut oder schlecht den Studenten es gefallen hat, das die Praktika online waren. Oder ist so was schon dabei?

**Comment by cyildiz** [comment]
In welcher Reihenfolge konsummieren Sie die Lehrmaterialien?
z.B.
[1] Videos
[2] Notizen/Skript
[3] Kahoot / ILIAS-Selbsttest
[4] Übungs- bzw. Praktikumsblatt
[5] Lernziele
[6] Literatur

Weiss nicht, wie man das in der Umfrage unsetzen könnte.

**Comment by cagix** [comment]
> Weiss nicht, wie man das in der Umfrage unsetzen könnte.

in gewisser weise wäre das in der obigen frage "welche materialien nutzen sie" mit enthalten, nur hier noch feiner aufgelöst (zusätzliche reihenfolge).

ich glaube, sowas erlaubt das system nicht. in ilias/moodle wäre das ein zuordnungsfrage, aber das evasys kennt sowas afaik nicht. aber wir könnten das zumindest anfragen.


> Eine offene Frage wäre auch möglich: In welcher Reihenfolge und auf welche Weise konsumieren Sie die angebotenen Materialien? Hätten Sie Änderungs- bzw. Verbesserungsvorschläge?

finde ich gut. das könnte dann die folgefrage zu "welche materialien nutzen sie" sein, und durch die offene frage bekommen wir vielleicht inhaltliches feedback ...

**Comment by cagix** [comment]
so, ich hätte dann die folgenden fragen. passt das so? soll ich das an felix so weiterleiten? fehlt noch was?

---


1.  Welche der angebotenen Materialien haben Sie zum Lernen und zum Lösen der Übungsblätter regelmäßig genutzt?

    |                            | immer | oft | selten | nie | keine Antwort |
    |----------------------------|-------|-----|--------|-----|---------------|
    | Skript (Webseite, Notizen) |       |     |        |     |               |
    | Videos                     |       |     |        |     |               |
    | Kahoot-Tests               |       |     |        |     |               |
    | Selbsttests ILIAS          |       |     |        |     |               |
    | Aufgabenblatt              |       |     |        |     |               |
    | Lernziele                  |       |     |        |     |               |
    | Literatur                  |       |     |        |     |               |


2.  In welcher Reihenfolge und auf welche Weise konsumieren Sie die angebotenen Materialien ([1] Skript (Webseite, Notizen), [2] Videos, [3] Kahoot-Tests, [4] Selbsttests ILIAS, [5] Aufgabenblatt, [6] Lernziele, [7] Literatur)? 

    Haben Sie Änderungs- bzw. Verbesserungsvorschläge?

    (Freitext)


3.  Wie hat Ihnen das Format "Flipped Classroom" gefallen? Was würden Sie sich zusätzlich zu den bisherigen Angeboten von der Sprechstunde wünschen?

    (Freitext)


4.  Wir hatten Ihnen angeboten, in den Praktika/Übungen die Hochschule zu wechseln und so stärker in einen interkulturellen Austausch zu gelangen. Wie beurteilen Sie dieses Angebot? 

    Was wäre für Sie ein Anreiz, am Praktikum oder an der Übung an der jeweiligen Partnerhochschule teilzunehmen?

    (Freitext)


5.  Die Praktika wurden aus verschiedenen Gründen online durchgeführt. Wie bewerten Sie dies?

    (Freitext)

**Comment by cyildiz** [comment]
Sieht so ganz gut aus.

**Comment by cagix** [comment]
Umfrage ist online. Danke für die Mitarbeit :)
