### ISSUE TITLE
[BUG]  A* Quiz mistakes

### ISSUE THREAD

**Issue by Ironeer** [KI-Vorlesung/Lecture#137]
**Describe the bug**
Das Quiz über A* bietet laut Vorlesungsfolien keine korrekte Antwort an.

**Screenshots**
Frage im Quiz zu Zulässigkeit:
![grafik](https://user-images.githubusercontent.com/19492236/151008672-69e02e2a-c219-4950-8382-d721fa981605.png)
In den Folien:
![grafik](https://user-images.githubusercontent.com/19492236/151008772-12d60a00-7463-4c51-a8a5-21d169831ee4.png)

Frage im Quiz zu Konsistenz:
![grafik](https://user-images.githubusercontent.com/19492236/151008465-77a57c5d-50fd-410d-bbaa-70038e0ded71.png)
In den Folien:
![grafik](https://user-images.githubusercontent.com/19492236/151008597-da1c217b-c69c-4ce6-a512-facb753f0bc6.png)

**Comment by cagix** [comment]
@Ironeer Danke für den Bug! Da fehlen in ILIAS tatsächlich die "<=" ...

**Comment by cagix** [comment]
@cagix zu fixen:

- [ ] Text in den Fragen im ILIAS
- [ ] Text in den Kahoot-Fragen
- [ ] Markdown im Quizzes-Repo

**Comment by cagix** [comment]
@Ironeer Sollte im ILIAS behoben sein. Bitte bei Gelegenheit kurz prüfen und kurzes Feedback. Danke!

**Comment by cagix** [comment]
@Ironeer Der Bug sollte behoben sein, ich schließe das Ticket jetzt. Bitte im ILIAS prüfen und bei Bedarf dieses Ticket bitte einfach wieder aufmachen.

**Comment by Ironeer** [comment]
Leider hat der fix nicht funktioniert:
![grafik](https://user-images.githubusercontent.com/19492236/151124209-5cb2940b-b9d7-4c6f-8e0a-106221396317.png)
![grafik](https://user-images.githubusercontent.com/19492236/151124259-26531c58-665c-4116-9621-55d1cb17bbd6.png)

@cagix  Ich kann das issue mangels Rechten leider nicht erneut öffnen

**Comment by cagix** [comment]
ugh. der screenshot ist ja sogar eine verschlechterung?! was ist denn da passiert?

**Comment by cagix** [comment]
Das hab ich ja auch noch nicht erlebt :/  ILIAS weigert sich, die Texteingaben für die Antworten korrekt zu speichern -- nach dem Speichern (keine Fehlermeldung!) wird einfach ein komplett anderer String angezeigt (in dem Fall "h(n)") ... 

Habe jetzt den Typ der Antwort im ILIAS modiziert und es sollte jetzt tatsächlich gefixt sein. Bitte nochmal prüfen :)

**Comment by cagix** [comment]
PS: Das ist ein ziemlich unerwartetes Fehlverhalten von ILIAS. Ich fürchte, dass deshalb in anderen Tests noch mehr von dieser Sorte Fehler steckt. Sry ...

**Comment by cagix** [comment]
@FinnAmini Das ist ein interessanter Bug im ILIAS, ich habe das mal an die IT gemeldet. 

Bitte bei Single-Choice-Fragen aufpassen, was wirklich gespeichert wird bzw. was nach dem Speichern noch da ist. 

Ich habe die Antworten in den beiden Fragen auf "mehrzeilige Antwort" umgestellt, und dann ging es. 

Trotzdem seltsam, weil der String jetzt nicht wirklich lang war und es auch keine Fehlermeldung gab und auch nicht etwa abgeschnitten wurde, sondern stumpf etwas ersetzt wurde ...

**Comment by Ironeer** [comment]
@cagix Technisch funktioniert jetzt alles, fachlich müsste es glaube ich `h(n) <= c(n, a, m) + h(m)` sein statt `- h(m)` wenn ich es mit dem Screenshot aus der Vorlesung vergleiche:
![grafik](https://user-images.githubusercontent.com/19492236/151130931-49405093-9785-4763-b2fe-8569c41d9827.png)
![grafik](https://user-images.githubusercontent.com/19492236/151130945-0c9aacf7-32aa-4ef4-a79d-a73ea7e5104a.png)

> PS: Das ist ein ziemlich unerwartetes Fehlverhalten von ILIAS. Ich fürchte, dass deshalb in anderen Tests noch mehr von dieser Sorte Fehler steckt. Sry ...

Kein Problem, wenn man ILIAS vernünftig haben will müsste man es ja eh selbst neu bauen^^

**Comment by cagix** [comment]
oh mann ... jetzt hab ich noch copy&paste gemacht ... 

so, jetzt aber :)

**Comment by cagix** [comment]
> Kein Problem, wenn man ILIAS vernünftig haben will müsste man es ja eh selbst neu bauen^^

dazu sag ich jetzt mal nix ;)

**Comment by Ironeer** [comment]
Passt jetzt alles 👍

**Comment by cagix** [comment]
@Ironeer mange takk!
