### ISSUE TITLE
[BUG] Blatt 06 - Wurzel wird nicht angezeigt

### ISSUE THREAD

**Issue by pfortmann** [KI-Vorlesung/Lecture#138]
**Describe the bug**
In der ersten Aufgabe wird dritte Gewichtsvektor nicht mehr angezeigt.

**Screenshots**

![6 1](https://user-images.githubusercontent.com/32076057/151186793-294bfab2-ea29-4b78-a4f9-aeb6af91b7d8.png)

**Comment by cagix** [comment]
kann ich (leider) bestätigen, werde mich auf die Suche machen ...

**Comment by cagix** [comment]
@pfortmann Sollte gefixt sein. Bitte nochmal im ILIAS prüfen (Cache leeren, Reload im Browser) und das Ticket ggf. nochmal aufmachen :)

**Comment by pfortmann** [comment]
Jetzt wird es beim mir wieder angezeigt, danke :)

**Comment by cagix** [comment]
war ne schräge sache, pandoc hat im ersten schritt die mathe-umgebung nicht erkannt und das escaped an hugo weitergereicht. vielleicht war das auch eine sache durch ein neues pandoc-release -- wenn das so ist, dann könnte genau dieser fehler auch an anderen ähnlichen stellen nochmal auftauchen.

@cyildiz bitte bei den mathe-sachen kein leerzeichen nach dem startenden `$` und keines vor dem endenden `$`, scheinbar kriegt pandoc das (mittlerweile?) in den falschen hals. (liest sich aber schöner.)

**Comment by cagix** [comment]
> Jetzt wird es bei mir wieder angezeigt, danke :)

danke fürs melden!
