### ISSUE TITLE
Planung Inhalte und Anlegen der Grundstruktur

### ISSUE THREAD

**Issue by cagix** [KI-Vorlesung/Lecture#15]

**Comment by cyildiz** [comment]
Ich würde die Issues für Grundstruktur (Anlegen der Dateien und Folder) und die Planung des Ablaufes via Schedule/Fahrplan trennen. 
Nach langem hin und her habe ich jetzt eine erste Version der Ordnerstruktur.

**Comment by cagix** [comment]
> Ich würde die Issues für Grundstruktur (Anlegen der Dateien und Folder) und die Planung des Ablaufes via Schedule/Fahrplan trennen.

ja, können wir gern trennen.

ich hatte gedacht, dass die initiale ordnerstruktur dann auch gleich in den schedule könnte und dann als weitere basis allen arbeiten zur verfügung steht. 


> Nach langem hin und her habe ich jetzt eine erste Version der Ordnerstruktur.

siehe meinen kommentar in https://github.com/KI-Vorlesung/Lecture/pull/32#issuecomment-919753377: du schlägst 7 neue hauptordner im menü vor, das wird etwas viel/unübersichtlich. mein vorschlag wäre, einen hauptordner "ml" im menü zu haben und die sieben "mlX" darunter zu schieben und thematisch zu benennen, damit man auch in der ordnerstruktur erkennt, worum es grad geht. vielleicht kann man ein oder zwei dieser ordner nochmal als unterkategorie zusammenfassen?
