### ISSUE TITLE
Orga - TDU

### ISSUE THREAD

**Issue by cyildiz** [KI-Vorlesung/Lecture#23]
Organisatorische Details für TDU-Studierende aufbereiten.

Letztes Jahr wurde eine Notion-Seite erstellt und mit den Studierenden geteilt:
https://cyildiz.notion.site/INF701-KI-Syllabus-76cd1ffb1fee4cbf9a5442a844670ed8

**Comment by cagix** [comment]
siehe auch #22

**Comment by cagix** [comment]
@cyildiz habe deine details zu übung und prüfung via #44 mit aufgenommen.

habe auch die literatur abgeglichen. bei den verweisen auf die kurse bin ich mir unsicher, die gehen ja teilweise deutlich über unseren kurs hinaus und die studis werden vermutlich gar keine zeit haben, sich damit auseinander zu setzen? 

kannst ja mal drauf schauen :)

**Comment by cagix** [comment]
in #48 habe ich die übungsleiter- und prüfungshinweise testhalber mal gesplittet. gefällt mir ganz gut. 

@cyildiz was denkst du?

**Comment by cyildiz** [comment]
Sieht alles super aus, vielen vielen Danl nochmal!

Auf der Hauptseite steht an einigen Stellen ILIAS als LMS. Wie könnten wir hier nun Google Classroom am besten hinzufügen?
Bei Wie-an-Sie z.b. eine Ebene tiefer gehen und:
- @FHB: News im ILIAS
- @TDU: News in Google Classroom
Was meinst Du?

**Comment by cagix** [comment]
Ja, genau. Oder einfach in Klammern? Also ein Stichpunkt "* ... ILIAS (@FHB), Google Classroom (@TDU), ..."?

**Comment by cagix** [comment]
hab mir das grad nochmal gerendert angeschaut, ich glaube, es sieht "schöner" aus in einem Stichpunkt, also 

```
-   **Wir-an-Sie**: "News" im ILIAS (@FHB) bzw. im Google Classroom (@TDU), Antwort auf Issues
```
