### ISSUE TITLE
Fahrplan - Graphische Übersicht

### ISSUE THREAD

**Issue by cyildiz** [KI-Vorlesung/Lecture#25]
Den graphischen Zeitplan in den Fahrplan, oberhalb der Wochenplan-Tabelle hinzufügen

**Comment by cagix** [comment]
@cyildiz kannst du bitte die graphik noch in einer version ohne das "plan a" auf der linken seite bereit stellen? ich könnte das ausschneiden, aber dann wird das bild neu gerendert und wird dadurch leicht pixelig.

wir könnten die graphik entweder auf der landing-page oder im schedule über der tabelle einbauen. was denkst du?

**Comment by cyildiz** [comment]
Ich hatte die Version ohne Plan A bereits fertig geschnitten und über die Tabelle eingefügt. Dann habe ich aber auf der Graphik selber noch einige Verbesserungen durchführen wollen und habe es daher nicht hochgeladen. Kann ich aber morgen Abend gleich machen.
Über der Tabelle könnte besser sein. Oder vielleicht anbiedern Stellen?

**Comment by cagix** [comment]
hmmm, ich denke 1x reicht ... zumal das bild wegen der hugo-ordnerstrukturen dann zweimal abgelegt werden müsste

**Comment by cagix** [comment]
am besten du comittest das nochmal, direkt auf dem aktuellen orga-branch. hat sich ja alles in der zwischenzeit weiter entwickelt, d.h. der alte commit passt nicht mehr

**Comment by cyildiz** [comment]
Dıe Graphik auf die Startseite, aber wohin?
Unter "Sprechstunde" zum Beispiel?

**Comment by cagix** [comment]
Ich würde es direkt zwischen die Überschriften `## Kursformat` und `### Vorlesung: 2 SWS` setzen. Das könnte ganz gut passen, dort sprechen wir ja über das Format und da passt ein Vorgeschmack auf den Zeitplan imho ganz gut :)

> Unter `markdown` einen Ordner `images` erstellen?

Probier mal, ob das geht. Die Landing-Page ist ja was "spezielles" in Hugo. Alternativ könntest Du das Bild einfach direkt unter `markdown/` packen, es ist ja nur das eine Bild, da ist ein extra Ordner vielleicht etwas "too much"?
