### ISSUE TITLE
Orga: Abgabe Übungsblätter

### ISSUE THREAD

**Issue by cagix** [KI-Vorlesung/Lecture#52]
@cyildiz Wann wollen wir die Abgabe der Lösungen machen? 

Die Praktika liegen bei uns beide auf dem Mittwoch, d.h. für mich könnte alles **_bis_ Mittwoch 09:00 Uhr** funktionieren. 

Wann sind bei euch die Übungen?

**Comment by cyildiz** [comment]
Bei uns steht das Programm noch nicht fest. In der Draft-Version liegt die UE auf dem Donnerstag. Ich habe jetzt nachgefragt, ob man es auf den Mittwoch fixieren kann. Mal sehen...

**Comment by cagix** [comment]
@cyildiz Donnerstag passt doch auch gut für die Übung :)  Dann könnten wir als Abgabe Mittwoch 9 Uhr setzen oder so ... 

Wenn wir die Abgabe früher machen müssen, dann könnte es allerdings etwas eng werden mit der Zeit zwischen Sprechstunde (Montag) und Abgabe. Aber das sehen wir dann ja ...

**Comment by cyildiz** [comment]
Ok, der aktuelle Plan steht jetzt so wie es aussieht.
Ein Wechsel auf Mittwoch scheint nicht möglich. Dann bleibt die UE bei uns am Donnerstag. 👍

**Comment by cagix** [comment]
ok, dann würde ich als abgabedatum im schedule den mittwoch lassen, da wir die praktika am mittwoch haben. dann haben deine studis einen tag weniger, aber das sollte noch passen, oder?

**Comment by cyildiz** [comment]
ich vermute, dass die studis immer nach extra zeit bis zur übungsstunde am nöchsten tag nachfragen werden :)

**Comment by cagix** [comment]
wenn wir im schedule "mittwoch" stehen haben, kannst du ja im google classroom "mittwoch 23:55 uhr" einrichten ... ich würde im ilias dann "mittwoch 09:00 uhr" einrichten, und dann passt es für beide :)  was denkst du?

**Comment by cyildiz** [comment]
Gute Idee!
Am nächsten Tag sind ja auch andere Vorlesungen, die sie besuchen müssen. Da sollten sie die Bearbeitung der Blätter schon fertig haben.
Passt!
